#!/bin/bash
# credit_simulator

PYTHON="python"
MAIN_SCRIPT="main.py"

if [[ "$1" == "input_file="* ]]; then
    INPUT_FILE="${1#*=}"
    shift 1

    $PYTHON $MAIN_SCRIPT "$INPUT_FILE" "$@"
else
   $PYTHON $MAIN_SCRIPT "$@"
fi


