name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  preparation_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: make test-with-coverage-html

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage_html_report

      - name: Check coverage threshold
        run: |
          COVERAGE_THRESHOLD=80
          COVERAGE=$(awk -F"[ %]+" '/^TOTAL/{print $3}' coverage_html_report/index.html)
          if (( $(echo "$COVERAGE < $COVERAGE_THRESHOLD" | bc -l) )); then
            echo "Coverage is below the threshold of $COVERAGE_THRESHOLD% ($COVERAGE%)."
            exit 1
          fi

  build_and_push:
    needs: preparation_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/credit-simulator:latest



